### ISSUE TITLE
Show counterpart info for Trades

### ISSUE THREAD

**Issue by narve** [euniversal/umei-api-specification#17]
How much information should be exposed when querying trades? What should be part of the API?

**Comment by cdmNSIDE** [comment]
Hello Narve,

If I understood well, what you would like to do is to add in the output of the tool an information saying which order (ex: buy order) is the counterpart of the order selected (ex: sell order). Right ?
I am not sure it's relevant for the auctions/markets planned in the demos of EUniversal.
There isn't a 1:1 relation between the orders. A buy order could for instance be matched with multiples sell orders, or parts of sell orders.

**Comment by narve** [comment]
The same goes for NODES: There's usually a one-to-one correspondence between buy- and sell-order, but not always. 

However, for "trades" the situation is different. One order can result in one or more trades. A trade is always between two parties, either between a buyer/seller and the FMO, or a direct trade between a buyer and a seller. 

We have an endpoint for showing trades, but that model does not show any counterpart information. For NODES, that is sufficient, we don't usually show much counter part information. If N-side is fine with leaving it as it is for now we can close this issue.
