### ISSUE TITLE
Specify a minimum set of search parameters / query parameters

### ISSUE THREAD

**Issue by narve** [euniversal/umei-api-specification#18]
Several of the endpoints, e.g. /orders, should accept filters to limit the search results. 

Some general seach filters are: 
- Take/Maxhits/Limit, to say how many hits you want returned
- StartFrom/Skip, to get the next "page" of data if there are more hits than returned. 

Examples of more specific filters: 
- portfolioId, for order-searches (/orders)
- orderId, for trade-searches (/trades)
- name, for portfolio-searches (/portfolios)

This issue is about whether we should specify any of these filters as part of the initial UMEI specification or not. If not, each FMO will still have to implement these filters, and it will be in inconsistencies between different FMOs.

**Comment by cdmNSIDE** [comment]
Hello Narve,

In my opinion, defining a list of filters for the search queries is something required to improve the robustness of the market platform. The underlying question is therefore to know what is the minimal robustness that we want to / must achieve in the framework of this project ...
I would try to keep it as simple as possible.
I think that an important filter to have is to limit the results returned depending on the access rights of the entity who submit the request.

**Comment by narve** [comment]
Filter on access rights are implicit - I don't think we need any API changes to support that?

**Comment by narve** [comment]
@cdmNSIDE see updated description. What do you think? I can come up with a proposal if you agree that we should include some of this.
