### ISSUE TITLE
Non unique operation id for the delete request of meter reading(s)

### ISSUE THREAD

**Issue by cdmNSIDE** [euniversal/umei-api-specification#2]
Ligne 722: operationId: MeterReading_Delete ---> to delete one meter reading
Ligne 782: operationId: MeterReading_Delete ---> to delete all meter readings ---> could me replaced by operationId: MeterReadings_Delete

**Comment by narve** [comment]
Please provide a pull request :)

**Comment by cdmNSIDE** [comment]
Yes I am on it ;)

**Comment by cdmNSIDE** [comment]
Hello Narve,
I created a pull request in NODES-Tech/umei-api-specification
Should it rather be in euniversal/umei-api-specification ?

**Comment by narve** [comment]
hm yes, that would be better.

**Comment by narve** [comment]
In fact maybe I should delete the original repository... but at least ignore the old repository for now.
