### ISSUE TITLE
Documentation for the UMEI

### ISSUE THREAD

**Issue by carlosdamassilva** [euniversal/umei-api-specification#26]
Should the UMEI have a support document for the D2.5? To be checked (E-REDES).

**Comment by carlosdamassilva** [comment]
There should be a simple document mentioning the goals, methodology, accomplishments, etc
The github content should be annexed to this document as well

**Comment by narve** [comment]
I would recommend that this document is written in markdown-format, as part of this repository. 
It will then be available in HTML format, and can be included in the automatically generated PDF.

**Comment by cdmNSIDE** [comment]
Hi Narve, I think we can close this issue as D2.5 is finished, no ?
