### ISSUE TITLE
Usage of customProperties in the Trade object

### ISSUE THREAD

**Issue by cdmNSIDE** [euniversal/umei-api-specification#34]
Hello @narve ,

Could you please explain why do we need to have the field "customProperties" in the "Trade" object?

`"customProperties": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            },
            "nullable": true
          }`

**Comment by narve** [comment]
No, it is a left-over from NODES, where we support custom properties on trade and order objects. I will remove it.

**Comment by narve** [comment]
See #39
