### ISSUE TITLE
Set additionalProperties to false

### ISSUE THREAD

**Issue by cdmNSIDE** [euniversal/umei-api-specification#35]
Hello @narve ,
In this https://apisecurity.io/encyclopedia/content/oasv3/datavalidation/schema/v3-schema-object-additionalproperties-true.htm, there is the following recommendation:

> In general, the safest option is not to allow additional properties. If the schema does not use allOf, anyOf, or oneOf at all, make sure you define all properties of the accepted JSON payload in the schema itself, and set additionalProperties to false.

What do you think of putting additionalProperties to false for all the objects in components/schemas ?

**Comment by narve** [comment]
I don't think that is viable in our case. If you provide a OpenAPI specification for your own API, then you can be strict with the schema. However, the UMEI specification is a subset of each FMOs capabilities. Each FMO may provide extra functionality. 

For instance, in NODES a DSO may provide orders which have a certain visiblity setting. This is rather NODES-specific and should probably not be part of the UMEI specification. 

If we restrict the order objects in UMEI (by setting additionProperties to false) then we force participants to use non-UMEI-endpoints when they need to specify those FMO-specific fields. In practise, that would entice participants to use non-UMEI-endpoints for all requests, thus preventing the adoption of UMEI.

**Comment by cdmNSIDE** [comment]
Thanks for the explanation ! 

At the moment in the UMEI, additionalProperties is set to false for:
- TradeSearchResult
- Link
- MeterReadingSearchResult
- OrderSearchResult
Should we put it back to true for those entities ?
By the way, since the default value for additionalProperties is true, can't we simply remove it everywhere ?

**Comment by narve** [comment]
Regarding the search results, no I don't think we should use additionalProperties = false. There are some required "universal" properties, in particular "numberOfHits". In addition, NODES API provides more information inside this object than is covered by the UMEI specification. 

Regarding additionalProperties=true: Yes, we can remove that as that is the default.
