### ISSUE TITLE
Review status of MeterReadings, Baselines, Portfolios and Orders

### ISSUE THREAD

**Issue by cdmNSIDE** [euniversal/umei-api-specification#36]
Hello @narve ,

At the moment, MeterReadings, Baselines, Portfolios and Orders can have 7 different values for the status:  Received, Pending, Rejected, Active, Inactive, Completed, Deleted.
Do you think that all those status are required? I guess it's the case for the Orders, but I am less sure for the other elements.
I would prefer to remove the statuses that are not strictly needed.

Would it also be possible to add a small description to explain the meaning of the different statuses ?
For instance, what does an "inactive" order mean ? An order selected in the reservation market but not in the activation market ?
What does "completed" mean ? Does that mean that the delivery period of the order is over ?

**Comment by narve** [comment]
@narve  Write a description of the statuses, and explain when and why they are used. State that each FMO can have specific rules regarding the statuses. State error codes if applicable

**Comment by narve** [comment]
See #52  - I think that should suffice, what do you think @cdmNSIDE ?
