### ISSUE TITLE
Search filter using the time intervals

### ISSUE THREAD

**Issue by cdmNSIDE** [euniversal/umei-api-specification#43]
Hello @narve ,
Do you think we need to add a filter to search orders (for instance) within a given time interval ?
I haven't added this specific filter in the PR that has already been merged, but at the last meeting I think you said you may want to add such a filter

**Comment by narve** [comment]
Yes, I think we need this one. I will try to free some time and create a PR.

**Comment by narve** [comment]
Time intervals, or timestamps, are in general not well suited for "equals" comparison. However, we assume rounding, e.g. to nearest second, will be used by the UMEI FMOs. We still need ranges, to support e.g. baselines that start between 1200 or 1300. 

In NODES API we model this using name of the property and a suffix plus a date in ISO format, e.g. 

   ...?PeriodFrom.StartOnOrAfter=2021-12-13T13:00Z
   ...?PeriodFrom.EndBefore=2021-12-13T14:00Z

We need both inclusive and exclusive boundaries. Furthermore, we might consider following the ODATA standard somewhat closer, and get less typing, by using: 
GT for Greater Than (=After)
GTE (or GE) for Greater Than Or Equal (=OnOrAfter)
LT for Less Than (=Before)
LTE (or LE) for Less Than Or Equal (=OnOrBefore)

**Comment by narve** [comment]
@ArnaudDebray @cdmNSIDE any comments / opinions?

**Comment by cdmNSIDE** [comment]
I would indeed go for the GT, GTE, LT, LTE standard. I don't see any other point of attention. 
I think this filter must be added in most of the search endpoints.

I am really sorry but I won't have time to create a PR on that topic before Christmas. Is it still possible on your side ?

**Comment by narve** [comment]
See #48
