### ISSUE TITLE
Reactive power, active power, and linked orders

### ISSUE THREAD

**Issue by narve** [euniversal/umei-api-specification#46]
In order to support reactive power, we should add a field, .e.g QuantityType, to the Market model. This type can have one of several values: ReactivePower, [Active]Power, Energy, Capacity, ... 

In the first version we don't consider linking activepower orders with reactivepower orders. We need to examing whether this linking will be required for the business cases that are part of our demos, or whether we can drop this requirement for now.

**Comment by narve** [comment]
I wil create PR for the new field in Market, plus documentation and glossary.

**Comment by narve** [comment]
@OysteinDE  can you find who can answer regarding the requirements for linking?

**Comment by michal-konopinski** [comment]
I like the idea with a separate market for reactive power / energy.
No need to link orders in the Polish demo.

**Comment by narve** [comment]
PR is merged. Order linked is postponed.
