### ISSUE TITLE
Add N-SIDE colleague on the github

### ISSUE THREAD

**Issue by cdmNSIDE** [euniversal/umei-api-specification#60]
Hello @narve . Could you please give access to my colleague Prateeba (pru@n-side.com) to this github?
I don't think I can do it by myself.
She is working on the Portuguese demo

Best regards,
Chloé

**Comment by narve** [comment]
sure, I can try. What is her username?

**Comment by cdmNSIDE** [comment]
Her username is pruN-SIDE
Thanks :)

**Comment by narve** [comment]
I invited her now.
