### ISSUE TITLE
Order Status are not detailed enough

### ISSUE THREAD

**Issue by narve** [euniversal/umei-api-specification#85]
Some market participants have reported that the current statuses allowed in UMEI are not detailed enough for their use cases. 

In the NODES API, we have an additional order status field, called OrderCompletionType, which says _why_ an order is "Completed" (no longer active): It can be Filled, Killed, Expired, or Cancelled. 

Another option is to have more allowable values for the status field, e.g. adding (at least) Expired and Cancelled as possible values. 

The advantage of having two fields are: 
- For other data types (e.g. portfolios) the OrderCompletionType and its values do not make sense (a "Killed" portfolio does not make sense)
- It is easier to distinguish between the two most "interesting" states an order can be in: Is it Active (as in, it is a passive order in the market), or is it not? (it is then Completed). 

The disadvantage is of course that users need to look at two fields to find out what happened to a previously active order - was it filled, was it cancelled, or did it expire? 

The advantage of having one field with several values is that it might be easier to understand for API users. However, the FMO then should document which statuses each data type can possibly be in (e.g., the status of a portfolio is either Active or Inactive, etc.

**Comment by narve** [comment]
In conclusion, NODES recommend that we add the OrderCompletionType enumeration and a new field CompletionType to the Order model. 

It is also acceptable to add the other statuses to the UMEI Status enumeration. But we probably need to do something to address the needs of the market participants. 

@cdmNSIDE @GiancarloNSIDE @vladimirvrabely what do you think?

**Comment by cdmNSIDE** [comment]
Hello @narve,
I do not see any objection on my side, but I would prefer to wait for the feedback of @ArnaudDebray (he will be back on Tuesday)

**Comment by OysteinDE** [comment]
Hi @cdmNSIDE and @ArnaudDebray

Any updates on this issue? Have you had a chance to look at it?

**Comment by ArnaudDebray** [comment]
No objection on my side in adding a field "CompletionType" to the Orders model. I think it's the best approach

**Comment by cdmNSIDE** [comment]
Ok for me as well. Note that we won't use those fields for our market platform in the context of the Portuguese demo
